# Generated by Django 3.0.8 on 2020-09-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200907_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
